version: '3.8'
services:
  frontend:
    image: jaikumargaja/form-app:latest
    ports:
      - "4000:4000"
    env_file:
      - ./form/.env
  backend:
    image: jaikumargaja/form-api:latest
    ports:
      - "5000:5000"
    env_file:
      - ./form-api/.env