pipeline {
    agent any
    
    environment {
        CLUSTER_NAME = 'devops-portfolio-cluster-v3'
        AWS_REGION = 'ap-south-1'
    }

    stages {
        stage('Update KubeConfig') {
            steps {
                // Jenkins automatically uses its EC2 IAM role here to authenticate
                sh "aws eks update-kubeconfig --region ${AWS_REGION} --name ${CLUSTER_NAME}"
                // aws eks update-kubeconfig --region ap-south-1 --name devops-portfolio-cluster-v3
            }
        }
        
        stage('Deploy to EKS') {
            steps {
                // Apply your YAML manifests
                sh "kubectl apply -f kubernetes/"
                
                // Force Kubernetes to pull the brand new Docker images
                sh "kubectl rollout restart deployment form-deployment form-api-deployment"
            }
        }
    }
}