pipeline {
    agent any
    
    environment {
        CLUSTER_NAME = 'devops-portfolio-cluster-v3'
        AWS_REGION = 'ap-south-1'
    }

    stages {
        stage('Update KubeConfig') {
            steps {
                // Jenkins automatically uses its EC2 IAM role here to authenticate
                sh "aws eks update-kubeconfig --region ${AWS_REGION} --name ${CLUSTER_NAME}"
                // aws eks update-kubeconfig --region ap-south-1 --name devops-portfolio-cluster-v3
            }
        }
        
        stage('Deploy to EKS') {
            steps {
                // 1. Pull the secret safely from Jenkins
                withCredentials([string(credentialsId: 'mongo-db-uri', variable: 'MONGO_URI')]) {
                    // 2. Safely create or update the secret in Kubernetes
                    sh "kubectl create secret generic app-secrets --from-literal=mongo-uri='${MONGO_URI}' --dry-run=client -o yaml | kubectl apply -f -"
                }
                
                // 3. Deploy the application
                sh "kubectl apply -f kubernetes/"
                
                // 4. Force restart to pull new images
                sh "kubectl rollout restart deployment form-api-deployment form-deployment"
            }
        }
    }
}